[package]
name = "cnn_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.15"
ndarray-rand = "0.14"
rand = "0.8"
plotters = "0.3"
image = "0.24"
minifb = "0.27.0"

[dependencies.mnist]
version = "0.6"
default-features = false
features = ["download"]